
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Dec 15 22:00:25 CET 2022
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CURLYPARLEFT = 10;
  public static final int AND = 12;
  public static final int MOREEQUAL = 22;
  public static final int CURLYPARRIGHT = 9;
  public static final int OR = 13;
  public static final int INT = 3;
  public static final int EQUAL = 24;
  public static final int NOTEQUAL = 23;
  public static final int SEMI = 17;
  public static final int CHAR = 4;
  public static final int LEFTPAR = 14;
  public static final int LOOP = 7;
  public static final int RIGHTPAR = 11;
  public static final int LESSEQUAL = 20;
  public static final int ID = 18;
  public static final int COMMA = 16;
  public static final int FLOAT = 5;
  public static final int EOF = 0;
  public static final int MORE = 21;
  public static final int MAIN = 2;
  public static final int CONST = 25;
  public static final int error = 1;
  public static final int ASSIGN = 15;
  public static final int BOOL = 6;
  public static final int REDO = 8;
  public static final int LESS = 19;
}

